services:
  - type: web
    name: shopify-infakt
    env: python
    envVars:
      - key: INFAKT_API_TOKEN
        fromEnvironment: INFAKT_API_TOKEN
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
